// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.IO;
using MckEstimatorML.Model;

namespace MckEstimatorML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            //ModelBuilder.CreateModel();
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleDataNisan1 = new ModelInput()
            {
                Prev_Close = 301.85F,
                Open = 307.50F,
                High = 309.80F,
                Low = 303.05F,
            };
            ModelInput sampleDataNisan5 = new ModelInput()
            {
                Prev_Close = 307.60F,
                Open = 307.90F,
                High = 311.65F,
                Low = 297.20F,
            };
            ModelInput sampleDataNisan6 = new ModelInput()
            {
                Prev_Close = 305.05F,
                Open = 305.60F,
                High = 313.90F,
                Low = 304.75F,
            };

            ModelInput sampleDataNisan7 = new ModelInput()
            {
                Prev_Close = 307.65F,
                Open = 307.25F,
                High = 310.75F,
                Low = 305.00F,
            };

            ModelInput sampleDataNisan8 = new ModelInput()
            {
                Prev_Close = 307.80F,
                Open = 308.55F,
                High = 319.75F,
                Low = 307.85F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult1 = ConsumeModel.Predict(sampleDataNisan1).Score;
            var predictionResult5 = ConsumeModel.Predict(sampleDataNisan5).Score;
            var predictionResult6 = ConsumeModel.Predict(sampleDataNisan6).Score;
            var predictionResult7 = ConsumeModel.Predict(sampleDataNisan7).Score;
            var predictionResult8 = ConsumeModel.Predict(sampleDataNisan8).Score;

            Console.WriteLine($"\n\nPredicted Last 1: {predictionResult1}\n\n");
            Console.WriteLine($"\n\nPredicted Last 5: {predictionResult5}\n\n");
            Console.WriteLine($"\n\nPredicted Last 6: {predictionResult6}\n\n");
            Console.WriteLine($"\n\nPredicted Last 7: {predictionResult7}\n\n");
            Console.WriteLine($"\n\nPredicted Last 8: {predictionResult8}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
